### Route for registration
POST http://localhost:4000/auth/users
Content-Type: application/json

{
    "firstName" : "Kavitha",
    "lastName" : "Gajawada",
    "email" : "kavithagajawada3@gmail.com",
    "password" : "abcdefghi",
    "role" : "ADMIN",
    "profileImageUrl" : "http://example.com"
}

### Route for login
POST http://localhost:4000/auth/login
Content-Type: application/json

{ 
    "email" : "samanvigajawada3@gmail.com",
    "password" : "abcdefghi"
}

### Route for logout
GET http://localhost:4000/auth/logout

### Read articles of all authors
GET http://localhost:4000/user-api/articles

### Add comment by user to an article
PUT http://localhost:4000/user-api/articles
Content-Type: application/json

{
    "articleId" : "69b4456fbedb0080fd77c64b",
    "comments" : "This article is useful"
}

### Change password
PUT http://localhost:4000/auth/password
Content-Type: application/json

{
    "currentPassword" : "Sanjana",
    "newPassword" : "Sahasra"
}